### ISSUE TITLE
Friday version

### ISSUE THREAD

**Issue by axman6** [phadej/JuicyPixels-scale-dct#2]
Hey phadej, I've made a version of this package which uses the `friday` package as its image type: [friday-scale-dct](https://github.com/axman6/friday-scale-dct). I thought you might be interested in taking a look. Nice work on the original library, it's been fun to play with.

**Comment by phadej** [comment]
Cool. I'll take a look!

**Comment by phadej** [comment]
Could you make a PR adding note about `friday-scale-dct` to the description and README.md of this package?

Also we could make this package work on other `Pixel`s of `JuicyPixels`; but I don't need that functionality myself atm.

**Comment by axman6** [comment]
Sorry for the late reply, I'll try and find time this weekend or early next week.

**Comment by axman6** [comment]
Hey I completely forgot about this, How do you feel about re-opening it, me fixing it and then closing it again? =)

**Comment by phadej** [comment]
@axman6 I added note to `friday-scale-dct` to the description at the newest version: http://hackage.haskell.org/package/JuicyPixels-scale-dct-0.1.1.1

Or was something else as well?

**Comment by axman6** [comment]
oh, nope, I hadn't seen that. Sorry for not doing it for you!

**Comment by phadej** [comment]
@axman6 np. Had to touch the lib anyhow :)
