### ISSUE TITLE
scaling seems to break with large images (>4MB)

### ISSUE THREAD

**Issue by nek0** [phadej/JuicyPixels-scale-dct#4]
Hi,

Ia am currently using your library to run the image scaling in my image gallery [eidolon](https://github.com/nek0/eidolon).
When encountering large photos, the scaling breaks and produces strange images like this one:
![broken kofi](https://cloud.githubusercontent.com/assets/1859691/18215194/531a585e-7150-11e6-83c2-23aae63b0153.jpg)

The original image for reference:
![kofi](https://cloud.githubusercontent.com/assets/1859691/18215277/bc6a0872-7150-11e6-9811-61eaa5cf46a1.jpg)

Am I doing something wrong, or is this a bug?

Thanks for your help.

nek0

**Comment by phadej** [comment]
It's a bug, Most likely there happens an floating point overflow (there is "sum all pixel values" op), after which everything goes bananas :S

I have to think how to mitigate that problem.

Thanks for the report, I didn't considered this case.

**Comment by phadej** [comment]
Can you try with a branch `issues-2-4`. I tried with a cat photo, and it seems to work on my machine at least. https://github.com/phadej/JuicyPixels-scale-dct/pull/5

**Comment by phadej** [comment]
Wait, it doesn't work. Have to check what's happening.

**Comment by phadej** [comment]
@nek0: Seems that problem is in `JuicyPixels` reading JPEG file. If I manually convert (with OSX preview.app) cat image to png, scaling works even without changes.

However if I with `JuicyPixels-3.2.7.2`, then the similar image to yours appears:

```
test = do
    Right dimg <- readImage "cat.png
    let img = convertRGBA8 dimg
    writePng "tmp.png" img
```

**Comment by nek0** [comment]
Thanks for looking into it. I'll refer to the JuicyPixels bugreport then.
